# Generated by Django 4.2.7 on 2023-11-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materials",
            name="is_publish",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="materials",
            name="slug",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="materials",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
